export const CREATE_POST = 'POST/CREATE_POST',
    FETCH_POST = 'POST/FETCH_POST',
    REQUEST_POSTS = 'POST/REQUEST_POSTS',
    SHOW_LOADER = 'APP/SHOW_LOADER',
    HIDE_LOADER = 'APP/HIDE_LOADER',
    SHOW_ALERT = 'APP/SHOW_ALERT',
    HIDE_ALERT = 'APP/HIDE_ALERT';